### PR TITLE
new scam link

### PR DESCRIPTION
**Pull request by vlfz**
domain/server info: https://check-host.net/ip-info?host=dicsord.gifts (idk if there's support for english)

image

### CODE REVIEW

**Comment by nonamemyna** [comment]
How the hell did you know my email

**Comment by vlfz** [comment]
> How the hell did you know my email

what

**Comment by MichailiK** [comment]
This is the point where you might want to delete your GitHub account @nonamemyna. Learn about how you can delete your GitHub account here: https://docs.github.com/articles/deleting-your-user-account

**Comment by Sanduhr32** [comment]
I'ld start by UNWATCHING the repo, because github sends emails like these if you watch a repo.

**Pull request closed without merging**
