### PR TITLE
[Hacktoberfest] added adsites, referrals, coin miners, scam domains in `referral_domains.txt`

### LINKED ISSUE #19: Hacktoberfest: More Referral Domains
For an overview of Hacktoberfest, [click here](https://hacktoberfest.digitalocean.com/).

For those of you interested in participating in Hacktoberfest, here is an opportunity for making contributions to Vortex! I am currently looking for pull requests to contribute to the referral/advertisement/ip-logger list. The current list can be found [here](https://github.com/jagrosh/Vortex/blob/hacktoberfest/lists/referral_domains.txt). 

Instructions:
1. Fork this repo.
2. Make changes to the referral_domains file (following the requirements below), and commit to your fork.
3. Open a pull request from your fork to the [`hacktoberfest` branch](https://github.com/jagrosh/Vortex/tree/hacktoberfest).
4. Include `[Hacktoberfest]` in the title of your PR.

Requirements:
1. Assuming you are contributing for the reasons outlined by this issue, your PR should only edit the file [found here](https://github.com/jagrosh/Vortex/blob/hacktoberfest/lists/referral_domains.txt) and should be opened onto the `hacktoberfest` branch.
2. You must add at least `5` valid domains for your PR to be accepted.
3. All domains must be root-only domains (no subdomains, like `images.google.com`; no paths, like `google.com/images`; no http/https, like `https://google.com`). If the root site is not a referral/ad/ip-logging site, please do not add it.
4. All domains must be _currently active_ referral, advertisement, or ip-logging sites. Please don't make a huge PR with 200 sites where half of them are old/outdated/etc; I check each site individually and if there are too many invalid sites in your list I will reject the PR. 
5. All domains must be unique. If multiple people PR the same domain, I will accept whichever comes first.
6. Domains must be organized following the existing system: organized by category, and alphabetized (roughly) within each category.
7. Use as few commits as possible (add all domains in one single commit, not one commit per domain). Additional commits should only be used if necessary for merging. Similarly, please keep all your added domains to one pull request.

### PR DESCRIPTION
**Pull request by RanadeepPolavarapu**
Resolves #19.

### CODE REVIEW

**Comment by jagrosh** [comment]
Can you alphabetize your additions

**Comment by RanadeepPolavarapu** [comment]
@jagrosh Sorry, what do you mean? Alphabetize the domains or the PR title?

**Comment by jagrosh** [comment]
The domains in the list

**Comment by RanadeepPolavarapu** [comment]
@jagrosh Done, please see if that is sufficient.

**Comment by jagrosh** [comment]
Thank you for your contribution!

**Comment by RanadeepPolavarapu** [comment]
@jagrosh Absolutely, you're welcome.

**Pull request merged**
