### PR TITLE
Domain doesn't work

### PR DESCRIPTION
**Pull request by greenbigfrog**
Not sure if you let your domain expire, or what happened, but the invite via your url sure doesn't work.

### CODE REVIEW

**Comment by jagrosh** [comment]
Whooops, one sec

**Comment by greenbigfrog** [comment]
Why didn't you just merge the PR?

**Comment by jagrosh** [comment]
Fixed with this commit: https://github.com/jagrosh/Vortex/commit/c803c24e25341631a39c7ec45541338e4f5ea023

**Comment by jagrosh** [comment]
Different permissions set and I didn't want to mask the link

**Pull request closed without merging**
